name: demo-lib
version: 0.1.0
description: ''
readme: README.md
authors:
  - charbonnierg <guillaume.charbonnier@araymond.com>

packages:
  - include: demo/
    from: src/

dependencies:
  - pydantic
  - pymongo
  - anyio
  - starlette
  - typer
